---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}"
    pre_build_image: true
    privileged: false
    command: ""

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        docker_users:
          - testuser
        docker_install_compose: true
        docker_compose_install_method: plugin
        # Skip actual Docker installation for testing
        docker_skip_service_start: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - syntax

lint: |
  set -e
  yamllint .
  ansible-lint .
