---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat)
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install basic requirements
      ansible.builtin.package:
        name:
          - curl
          - gnupg
          - ca-certificates
        state: present
