---
# Debian/Ubuntu specific tasks for Docker installation

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ _docker_gpg_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  register: _docker_gpg_key_download

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ _docker_arch_mapping[ansible_architecture] | default(ansible_architecture) }} signed-by=/etc/apt/keyrings/docker.asc] {{ _docker_repo_url }} {{ ansible_distribution_release }} {{ docker_release_channel }}"
    state: present
    filename: docker
    update_cache: true

- name: Remove old Docker packages if present
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
  when: not _docker_installed.stat.exists
