---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts.os_family == 'Debian'

    - name: Wait for systemd to complete initialization.
      ansible.builtin.systemd:
        name: systemd
        state: started
      register: systemctl_status
      until: systemctl_status is succeeded
      retries: 30
      delay: 1
      failed_when: false
      changed_when: false

  roles:
    - role: "ansible-role-docker"
