---
dependency:
  name: galaxy
  options:
    requirements-file: ../default/requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-22.04
    image: "ubuntu:22.04"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    dockerfile: ../resources/Dockerfile.j2
    networks:
      - name: molecule

provisioner:
  name: ansible
  inventory:
    host_vars:
      all:
        docker_users:
          - testuser
        docker_install_compose: true
        docker_compose_install_method: plugin
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
      stdout_callback: yaml

verifier:
  name: ansible
  additional_files_or_dirs:
    - ../default/verify.yml

lint: |
  set -e
  yamllint .
  ansible-lint .
